### ISSUE TITLE
t/widget.t fails (with HTML-Tree-5.04?)

### ISSUE THREAD

**Issue by eserte** [rjbs/MasonX-Resolver-WidgetFactory#1]
My smokers started to report the following failure:
```

#   Failed test 'content_explicit'
#   at /usr/perl5.20.1Dp/lib/site_perl/5.20.1/HTML/Mason/Tests.pm line 593.
# Looks like you failed 1 test of 6.
t/widget.t .................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/6 subtests 
```

There is no useful result from statistical analysis, but experimenting shows that the failure happens only if HTML-Tree-5.04 is installed.

**Comment by rjbs** [comment]
This appears to be fixed (fsvo fixed) in HTML-Tree.  Thanks for the report!
